dist: trusty
sudo: required

language: ruby

rvm:
  - 1.9.3
  - 2.2.3

addons:
  chrome: stable

before_install:
  - gem install bundler

before_script:
  - export DISPLAY=:99.0
  - chmod 777 ./config/ci/before-travis.sh
  - ./config/ci/before-travis.sh

script:
  - export DISPLAY=:99.0
  - bundle
  - EXTJS_SRC=cdn bundle exec rake

branches:
  only:
    - master
    - 0-12
