language: ruby
rvm:
  - 1.9.3
before_script: 
  - chmod 777 ./config/ci/before-travis.sh
  - ./config/ci/before-travis.sh
script:
  - export DISPLAY=:99.0
  - EXTJS_SRC=cdn bundle exec rake
branches:
  only:
    - master
    - 0-9
